# Generated by Django 4.1.7 on 2023-05-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub_app', '0007_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookmarkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games_hub_app.image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games_hub_app.rats')),
            ],
            options={
                'unique_together': {('user', 'image')},
            },
        ),
    ]
