# Generated by Django 4.1.7 on 2023-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_hub_app', '0008_image_bookmark_bookmarkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Pub_Date'),
        ),
    ]
